---
title: "Question 2 DB Setup - Coursework"
student_number: "190341259"
date: "2023-12-06"
output: html_document
---

```{r setup chunk, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Q2
## Database setup

## To access the project files to run this notebook

Check github (link: https://github.com/inc0gn1k0/submission_final_st2195.git) to access the entire project folder.

```{r Database Setup (Relative Paths)}
library(DBI)
library(RSQLite)
library(readr)
raw_path <- file.path(getwd(), '..', 'raw_data') #gets absolute path on your system directory, using file.path() which portable across systems. 
# the '..' represents parent directory of our script...which is submission_final, os.path.join() then points to our target folder 'raw data'

years <- 1997:2007 #database of 11 consec years, of which we will use 10 years.
list_of_our_csv_files <- paste0(raw_path, "/", years, ".csv")

supplementary_data_files <- c('plane-data.csv', 'airports.csv', 'carriers.csv', 'variable-descriptions.csv')
supplementary_table_names <- c('planes', 'airports', 'carriers', 'variable_descriptions')
list_of_supplementary_data <- setNames(paste0(raw_path, "/", supplementary_data_files), supplementary_table_names)

# Database setup
pathname <- file.path(raw_path, 'comp97to07.db')
conn <- dbConnect(RSQLite::SQLite(), dbname = pathname)
cat("\nCSV files stored and database initialized\n")

# Creating tables for my data CSV files....I use enumerate because we need to index, as we do not want all the data from the harvard dataverse...only a subset of 10 consec years
for (i in seq_along(list_of_our_csv_files)) {
  csv_file <- list_of_our_csv_files[i]
  table_name <- paste0("Y", years[i])
  df <- read_csv(csv_file, col_types = cols()) #, fileEncoding='ISO-8859-1') #this encoding format uses one byte per character...which allows us to keep a low memory footprint...
  dbWriteTable(conn, table_name, df, overwrite = TRUE, row.names = FALSE)
  cat(paste0("\nDatabase populated with ", table_name, "\n"))
  rm(df)
  gc() #free up memory
}

# Create tables for the supplementary data CSV files.....I used this so that I can unpack table and table name separately...
for (table_name in names(list_of_supplementary_data)) {
  csv_file <- list_of_supplementary_data[[table_name]]
  df <- read_csv(csv_file, col_types = cols()) #, fileEncoding='ISO-8859-1') #this encoding format uses one byte per character...which allows us to keep a low memory footprint...
  dbWriteTable(conn, table_name, df, overwrite = TRUE, row.names = FALSE)
  cat(paste0("\nDatabase populated with ", table_name, "\n"))
}

dbDisconnect(conn)

```

```{r Databse Setup (ABSOLUTE PATHS)}
# library(DBI)
# library(RSQLite)
# library(readr)
# 
# # List of our data CSV files
# list_of_our_csv_files <- c(
#     '/Users/admin/Desktop/My_Stuff/UOL_Course_Content/Academia/2024/ST2195/ST2195_coursework/raw_data/1997.csv',
#     '/Users/admin/Desktop/My_Stuff/UOL_Course_Content/Academia/2024/ST2195/ST2195_coursework/raw_data/1998.csv',
#     '/Users/admin/Desktop/My_Stuff/UOL_Course_Content/Academia/2024/ST2195/ST2195_coursework/raw_data/1999.csv',
#     '/Users/admin/Desktop/My_Stuff/UOL_Course_Content/Academia/2024/ST2195/ST2195_coursework/raw_data/2000.csv',
#     '/Users/admin/Desktop/My_Stuff/UOL_Course_Content/Academia/2024/ST2195/ST2195_coursework/raw_data/2001.csv',
#     '/Users/admin/Desktop/My_Stuff/UOL_Course_Content/Academia/2024/ST2195/ST2195_coursework/raw_data/2002.csv',
#     '/Users/admin/Desktop/My_Stuff/UOL_Course_Content/Academia/2024/ST2195/ST2195_coursework/raw_data/2003.csv',
#     '/Users/admin/Desktop/My_Stuff/UOL_Course_Content/Academia/2024/ST2195/ST2195_coursework/raw_data/2004.csv',
#     '/Users/admin/Desktop/My_Stuff/UOL_Course_Content/Academia/2024/ST2195/ST2195_coursework/raw_data/2005.csv',
#     '/Users/admin/Desktop/My_Stuff/UOL_Course_Content/Academia/2024/ST2195/ST2195_coursework/raw_data/2006.csv',
#     '/Users/admin/Desktop/My_Stuff/UOL_Course_Content/Academia/2024/ST2195/ST2195_coursework/raw_data/2007.csv'
# )
# 
# # List of supplementary data CSV files and their corresponding table names
# list_of_supplementary_data <- list(
#   c('/Users/admin/Desktop/My_Stuff/UOL_Course_Content/Academia/2024/ST2195/ST2195_coursework/raw_data/plane-data.csv', 'planes'),
#   c('/Users/admin/Desktop/My_Stuff/UOL_Course_Content/Academia/2024/ST2195/ST2195_coursework/raw_data/airports.csv', 'airports'),
#   c('/Users/admin/Desktop/My_Stuff/UOL_Course_Content/Academia/2024/ST2195/ST2195_coursework/raw_data/carriers.csv', 'carriers'),
#   c('/Users/admin/Desktop/My_Stuff/UOL_Course_Content/Academia/2024/ST2195/ST2195_coursework/raw_data/variable-descriptions.csv', 'variable_descriptions')
# )
# 
# # Connect to the SQLite database
# pathname <- '/Users/admin/Desktop/My_Stuff/UOL_Course_Content/Academia/2024/ST2195/ST2195_coursework/st2195_processedfiles/comp97to07.db'
# conn <- dbConnect(RSQLite::SQLite(), dbname = pathname)
# 
# # Creatin tables for my data CSV files
# for (i in 1:length(list_of_our_csv_files)) {
#   csv_file <- list_of_our_csv_files[i]
#   table_name <- paste0('Y', 1997 + i)
#   df <- read_csv(csv_file)
#   dbWriteTable(conn, table_name, df, overwrite = TRUE, row.names = FALSE)
# }
# 
# # Create tables for the supplementary data CSV files
# for (item in list_of_supplementary_data) {
#   csv_file <- item[1]
#   table_name <- item[2]
#   df <- read_csv(csv_file)
#   dbWriteTable(conn, table_name, df, overwrite = TRUE, row.names = FALSE)
# }
# 
# dbDisconnect(conn)

```


```