name: submission_final
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - r-base
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - ipykernel
  - notebook
  - statsmodels
  - scikit-learn
  - jupyterlab
  - r-essentials
  - r-dplyr
  - r-ggplot2
  - r-tidyr
  - r-readr
  - r-caret
  - r-randomForest
  - pip
  - pip:
      - dataframe_image
      - jupyterlab==3.*
      - seaborn==0.11.*
      - statsmodels
      - scikit-learn
      - matplotlib
